# Generated by Django 3.2.5 on 2022-01-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='users_wishlist',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
